### ISSUE TITLE
k pex bro

### ISSUE THREAD

**Issue by tekakutli** [ram535/dots#1]
accidentalmente note tu existencia
y tu estatus de usuario de emacs 
y como no hay muchos asi por aqui me pongo en contacto

**Comment by ram535** [comment]
Que tal, donde notaste mi existencia?

**Comment by tekakutli** [comment]
le diste like a org-fc 
estas en el discord de System Crafters?

**Comment by ram535** [comment]
si, estoy en system crafters discord. De que parte eres?

**Comment by ram535** [comment]
mi usuario es ram en el discord
